"""add briefings

Revision ID: 194106608213
Revises: 1227802db612
Create Date: 2026-08-11 22:41:53.345799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '194106608213'
down_revision: Union[str, None] = '1227802db612'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_incoming_messages_status_created_at', table_name='incoming_messages')
    op.drop_index('ix_incoming_messages_user_id', table_name='incoming_messages')
    op.drop_table('incoming_messages')
    op.add_column('users', sa.Column('briefing_time', sa.Text(), server_default='08:00', nullable=False))
    op.add_column('users', sa.Column('briefing_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('briefing_detail_level', sa.Text(), server_default='standard', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'briefing_detail_level')
    op.drop_column('users', 'briefing_enabled')
    op.drop_column('users', 'briefing_time')
    op.create_table('incoming_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('channel', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'pending'::text"), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.CheckConstraint("channel = ANY (ARRAY['whatsapp'::text, 'sms'::text, 'slack'::text, 'email'::text])", name='chk_incoming_messages_channel'),
    sa.CheckConstraint("status = ANY (ARRAY['pending'::text, 'processing'::text, 'done'::text, 'error'::text])", name='chk_incoming_messages_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='incoming_messages_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='incoming_messages_pkey')
    )
    op.create_index('ix_incoming_messages_user_id', 'incoming_messages', ['user_id'], unique=False)
    op.create_index('ix_incoming_messages_status_created_at', 'incoming_messages', ['status', 'created_at'], unique=False)
    # ### end Alembic commands ###
