"""phase5_3_intelligence_hardening

Revision ID: 2120cc501322
Revises: 59ee5acee259
Create Date: 2026-08-20 13:39:33.029800

"""

from typing import Sequence, Union

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2120cc501322"
down_revision: Union[str, None] = "59ee5acee259"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("preferences", sa.Column("scope", sa.String(), server_default="general", nullable=False))
    op.add_column("preferences", sa.Column("status", sa.String(), server_default="ACTIVE", nullable=False))
    op.add_column("preferences", sa.Column("supersedes_preference_id", sa.UUID(), nullable=True))
    op.add_column("preferences", sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True))
    op.add_column("preferences", sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True))
    op.add_column("preferences", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True))
    op.create_foreign_key(None, "preferences", "preferences", ["supersedes_preference_id"], ["id"])
    op.alter_column(
        "users",
        "autonomy_level",
        existing_type=sa.INTEGER(),
        type_=sa.String(),
        postgresql_using="autonomy_level::varchar",
        existing_nullable=False,
        existing_server_default=sa.text("2"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "autonomy_level",
        existing_type=sa.String(),
        type_=sa.INTEGER(),
        postgresql_using="autonomy_level::integer",
        existing_nullable=False,
        existing_server_default=sa.text("2"),
    )
    op.drop_column("preferences", "embedding")
    op.drop_column("preferences", "valid_until")
    op.drop_column("preferences", "valid_from")
    op.drop_column("preferences", "supersedes_preference_id")
    op.drop_column("preferences", "status")
    op.drop_column("preferences", "scope")
    # ### end Alembic commands ###
