"""phase5_memory_supersession

Revision ID: 394a58a35866
Revises: 5439402f75bb
Create Date: 2026-08-20 12:50:42.039017

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "394a58a35866"
down_revision: Union[str, None] = "5439402f75bb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("memory_entries", sa.Column("supersedes_memory_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        "fk_memory_entries_supersedes",
        "memory_entries",
        "memory_entries",
        ["supersedes_memory_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_memory_entries_supersedes", "memory_entries", type_="foreignkey")
    op.drop_column("memory_entries", "supersedes_memory_id")
    # ### end Alembic commands ###
