"""Add agent plan persistence

Revision ID: 3cecdc799c02
Revises: b6a4df3e91c2
Create Date: 2026-08-20 01:34:33.124330

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3cecdc799c02"
down_revision: Union[str, None] = "b6a4df3e91c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "agent_plans",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("conversation_id", sa.Text(), nullable=True),
        sa.Column("goal", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="CREATED", nullable=False),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('CREATED', 'VALIDATING', 'RUNNING', 'WAITING_FOR_CONFIRMATION', 'PAUSED', 'COMPLETED', 'FAILED', 'CANCELLED', 'EXPIRED')",
            name="chk_agent_plans_status",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_agent_plans_conversation_id"), "agent_plans", ["conversation_id"], unique=False)
    op.create_index(op.f("ix_agent_plans_status"), "agent_plans", ["status"], unique=False)
    op.create_index(op.f("ix_agent_plans_user_id"), "agent_plans", ["user_id"], unique=False)
    op.create_table(
        "agent_plan_steps",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("step_id", sa.Text(), nullable=False),
        sa.Column("tool_name", sa.Text(), nullable=False),
        sa.Column("arguments", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False),
        sa.Column("depends_on", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False),
        sa.Column("execution_mode", sa.Text(), nullable=False),
        sa.Column("risk_level", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default="CREATED", nullable=False),
        sa.Column("invocation_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "status IN ('CREATED', 'PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED')",
            name="chk_agent_plan_steps_status",
        ),
        sa.ForeignKeyConstraint(["invocation_id"], ["tool_invocations.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["plan_id"], ["agent_plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_agent_plan_steps_plan_id", "agent_plan_steps", ["plan_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_agent_plan_steps_plan_id", table_name="agent_plan_steps")
    op.drop_table("agent_plan_steps")
    op.drop_index(op.f("ix_agent_plans_user_id"), table_name="agent_plans")
    op.drop_index(op.f("ix_agent_plans_status"), table_name="agent_plans")
    op.drop_index(op.f("ix_agent_plans_conversation_id"), table_name="agent_plans")
    op.drop_table("agent_plans")
    # ### end Alembic commands ###
