"""phase5_2_personal_intelligence

Revision ID: 59ee5acee259
Revises: 394a58a35866
Create Date: 2026-08-20 13:15:25.402425

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59ee5acee259"
down_revision: Union[str, None] = "394a58a35866"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "preferences",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("preference", sa.Text(), nullable=False),
        sa.Column("confidence", sa.String(), server_default="MEDIUM", nullable=False),
        sa.Column("strength", sa.Float(), server_default="0.5", nullable=False),
        sa.Column("source", sa.String(), server_default="observed", nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_preferences_domain"), "preferences", ["domain"], unique=False)
    op.create_index(op.f("ix_preferences_user_id"), "preferences", ["user_id"], unique=False)
    op.add_column("memory_entries", sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True))
    op.add_column("memory_entries", sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memory_entries", "valid_until")
    op.drop_column("memory_entries", "valid_from")
    op.drop_index(op.f("ix_preferences_user_id"), table_name="preferences")
    op.drop_index(op.f("ix_preferences_domain"), table_name="preferences")
    op.drop_table("preferences")
    # ### end Alembic commands ###
