"""add_notifications_log_columns

Revision ID: 5dd5c3437bd4
Revises: a21f8c9e7b12
Create Date: 2026-08-13 06:34:19.822075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dd5c3437bd4'
down_revision: Union[str, None] = 'a21f8c9e7b12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_log', sa.Column('importance_score', sa.Float(), server_default='0.0', nullable=False))
    op.add_column('notification_log', sa.Column('dispatched', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_log', 'dispatched')
    op.drop_column('notification_log', 'importance_score')
    # ### end Alembic commands ###
