"""phase6_2_agentrun_cols

Revision ID: 697a9c81c116
Revises: f03ca82b5faf
Create Date: 2026-08-20 14:49:32.165714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '697a9c81c116'
down_revision: Union[str, None] = 'f03ca82b5faf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('autonomous', sa.Boolean(), nullable=False))
    op.add_column('agent_runs', sa.Column('triggered_by', sa.Text(), nullable=True))
    op.add_column('agent_runs', sa.Column('trigger_event_id', sa.Text(), nullable=True))
    op.add_column('agent_runs', sa.Column('workflow_id', sa.Text(), nullable=True))
    op.add_column('agent_runs', sa.Column('decision_id', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'decision_id')
    op.drop_column('agent_runs', 'workflow_id')
    op.drop_column('agent_runs', 'trigger_event_id')
    op.drop_column('agent_runs', 'triggered_by')
    op.drop_column('agent_runs', 'autonomous')
    op.create_index('ix_daily_usage_user_id', 'daily_usage', ['user_id'], unique=False)
    op.create_index('ix_daily_usage_date', 'daily_usage', ['usage_date'], unique=False)
    # ### end Alembic commands ###
