"""phase6_3_feedback

Revision ID: 75d0c83fa3f1
Revises: 697a9c81c116
Create Date: 2026-08-20 14:56:23.434663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d0c83fa3f1'
down_revision: Union[str, None] = '697a9c81c116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('workflow_id', sa.Text(), nullable=True),
    sa.Column('feedback_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_feedback_run_id'), 'decision_feedback', ['run_id'], unique=False)
    op.create_index(op.f('ix_decision_feedback_user_id'), 'decision_feedback', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_daily_usage_user_id', 'daily_usage', ['user_id'], unique=False)
    op.create_index('ix_daily_usage_date', 'daily_usage', ['usage_date'], unique=False)
    op.drop_index(op.f('ix_decision_feedback_user_id'), table_name='decision_feedback')
    op.drop_index(op.f('ix_decision_feedback_run_id'), table_name='decision_feedback')
    op.drop_table('decision_feedback')
    # ### end Alembic commands ###
