"""add eod briefings

Revision ID: c14eba281e84
Revises: 194106608213
Create Date: 2026-08-11 23:04:21.238535

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c14eba281e84"
down_revision: Union[str, None] = "194106608213"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("eod_briefing_time", sa.Text(), server_default="18:00", nullable=False))
    op.add_column("users", sa.Column("eod_briefing_enabled", sa.Boolean(), server_default="true", nullable=False))
    op.add_column("users", sa.Column("eod_briefing_detail_level", sa.Text(), server_default="standard", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "eod_briefing_detail_level")
    op.drop_column("users", "eod_briefing_enabled")
    op.drop_column("users", "eod_briefing_time")
    # ### end Alembic commands ###
