"""add direction and to_address to email_messages

Revision ID: d60b02f59d7f
Revises: c14eba281e84
Create Date: 2026-08-12 03:19:21.033099

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d60b02f59d7f"
down_revision: Union[str, None] = "c14eba281e84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("email_messages", sa.Column("to_address", sa.Text(), nullable=True))
    op.add_column("email_messages", sa.Column("direction", sa.Text(), server_default="inbound", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("email_messages", "direction")
    op.drop_column("email_messages", "to_address")
    # ### end Alembic commands ###
