"""Add prep_generated to calendar_events

Revision ID: d6834ace8c58
Revises: 5dd5c3437bd4
Create Date: 2026-08-13 07:14:23.808587

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd6834ace8c58'
down_revision: Union[str, None] = '5dd5c3437bd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('prep_generated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'prep_generated')
    # ### end Alembic commands ###
