"""phase6_2_workflows

Revision ID: f03ca82b5faf
Revises: 74a03c2a8ae9
Create Date: 2026-08-20 14:48:40.975096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f03ca82b5faf'
down_revision: Union[str, None] = '74a03c2a8ae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooldowns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('trigger_key', sa.String(), nullable=False),
    sa.Column('last_executed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cooldown_until', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooldowns_trigger_key'), 'cooldowns', ['trigger_key'], unique=False)
    op.create_index(op.f('ix_cooldowns_user_id'), 'cooldowns', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_daily_usage_user_id', 'daily_usage', ['user_id'], unique=False)
    op.create_index('ix_daily_usage_date', 'daily_usage', ['usage_date'], unique=False)
    op.drop_index(op.f('ix_cooldowns_user_id'), table_name='cooldowns')
    op.drop_index(op.f('ix_cooldowns_trigger_key'), table_name='cooldowns')
    op.drop_table('cooldowns')
    # ### end Alembic commands ###
