"""Add missing user columns

Revision ID: 9b87772b52d2
Revises: 0fed51b44101
Create Date: 2026-08-13 22:21:05.505382
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b87772b52d2'
down_revision: Union[str, None] = '0fed51b44101'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('source', sa.Text(), server_default='manual', nullable=False))
    op.add_column('calendar_events', sa.Column('google_event_id', sa.Text(), nullable=True))
    op.add_column('calendar_events', sa.Column('prep_generated', sa.Boolean(), server_default='false', nullable=False))
    op.create_unique_constraint('uq_calendar_events_user_google_event_id', 'calendar_events', ['user_id', 'google_event_id'])
    op.drop_constraint('integrations_user_id_fkey', 'integrations', type_='foreignkey')
    op.create_foreign_key(None, 'integrations', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('briefing_time', sa.Text(), server_default='08:00', nullable=False))
    op.add_column('users', sa.Column('briefing_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('briefing_detail_level', sa.Text(), server_default='standard', nullable=False))
    op.add_column('users', sa.Column('eod_briefing_time', sa.Text(), server_default='18:00', nullable=False))
    op.add_column('users', sa.Column('eod_briefing_enabled', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('users', sa.Column('eod_briefing_detail_level', sa.Text(), server_default='standard', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'eod_briefing_detail_level')
    op.drop_column('users', 'eod_briefing_enabled')
    op.drop_column('users', 'eod_briefing_time')
    op.drop_column('users', 'briefing_detail_level')
    op.drop_column('users', 'briefing_enabled')
    op.drop_column('users', 'briefing_time')
    op.drop_constraint(None, 'integrations', type_='foreignkey')
    op.create_foreign_key('integrations_user_id_fkey', 'integrations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_calendar_events_user_google_event_id', 'calendar_events', type_='unique')
    op.drop_column('calendar_events', 'prep_generated')
    op.drop_column('calendar_events', 'google_event_id')
    op.drop_column('calendar_events', 'source')
    # ### end Alembic commands ###

